[package]
name = "osrm-openapi-models"
version = "0.0.1"
authors = ["OpenAPI Generator team and contributors"]
description = "Open Source Routing Machine Models"
repository = "https://github.com/Rallista/osrm-openapi-rs"
license = "BSD-3-Clause"
edition = "2024"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_repr = "^0.1"
url = "^2.5"
uuid = { version = "^1.8", features = ["serde", "v4"] }
reqwest = { version = "^0.12", features = ["json", "multipart"] }

[lints.clippy]
empty_docs = "allow"
