/*
 * OSRM API v5.22.0
 *
 * Open Source Routing Machine Models
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Annotation {
    /// The distance, in metres, between each pair of coordinates
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<Vec<f64>>,
    /// The duration between each pair of coordinates, in seconds
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<Vec<f64>>,
    #[serde(rename = "datasources", skip_serializing_if = "Option::is_none")]
    pub datasources: Option<Vec<i32>>,
    #[serde(rename = "nodes", skip_serializing_if = "Option::is_none")]
    pub nodes: Option<Vec<i32>>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<Vec<i32>>,
    #[serde(rename = "speed", skip_serializing_if = "Option::is_none")]
    pub speed: Option<Vec<f64>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::AnnotationMetadata>>,
}

impl Annotation {
    pub fn new() -> Annotation {
        Annotation {
            distance: None,
            duration: None,
            datasources: None,
            nodes: None,
            weight: None,
            speed: None,
            metadata: None,
        }
    }
}

