/*
 * OSRM API v5.22.0
 *
 * Extended Open Source Routing Machine Models. This includes default OSRM models, plus optional fields like MaxSpeed.
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnotationMetadata {
    #[serde(rename = "datasource_names", skip_serializing_if = "Option::is_none")]
    pub datasource_names: Option<Vec<String>>,
}

impl AnnotationMetadata {
    pub fn new() -> AnnotationMetadata {
        AnnotationMetadata {
            datasource_names: None,
        }
    }
}

