/*
 * OSRM API v5.22.0
 *
 * Open Source Routing Machine Models
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BannerInstruction {
    #[serde(rename = "distanceAlongGeometry")]
    pub distance_along_geometry: f64,
    #[serde(rename = "primary")]
    pub primary: Box<models::BannerContent>,
    #[serde(rename = "secondary", skip_serializing_if = "Option::is_none")]
    pub secondary: Option<Box<models::BannerContent>>,
}

impl BannerInstruction {
    pub fn new(distance_along_geometry: f64, primary: models::BannerContent) -> BannerInstruction {
        BannerInstruction {
            distance_along_geometry,
            primary: Box::new(primary),
            secondary: None,
        }
    }
}

