/*
 * OSRM API v5.22.0
 *
 * Extended Open Source Routing Machine Models. This includes default OSRM models, plus optional fields like MaxSpeed.
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BannerContent {
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::ManeuverType>,
    #[serde(rename = "modifier", skip_serializing_if = "Option::is_none")]
    pub modifier: Option<models::ManeuverModifier>,
    #[serde(rename = "components", skip_serializing_if = "Option::is_none")]
    pub components: Option<Vec<models::BannerContentComponentsInner>>,
}

impl BannerContent {
    pub fn new(text: String) -> BannerContent {
        BannerContent {
            text,
            r#type: None,
            modifier: None,
            components: None,
        }
    }
}

