/*
 * OSRM API v5.22.0
 *
 * Extended Open Source Routing Machine Models. This includes default OSRM models, plus optional fields like MaxSpeed.
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Intersection {
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Vec<f64>>,
    #[serde(rename = "bearings", skip_serializing_if = "Option::is_none")]
    pub bearings: Option<Vec<i32>>,
    #[serde(rename = "classes", skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<String>>,
    #[serde(rename = "entry", skip_serializing_if = "Option::is_none")]
    pub entry: Option<Vec<bool>>,
    #[serde(rename = "in", skip_serializing_if = "Option::is_none")]
    pub r#in: Option<i32>,
    #[serde(rename = "out", skip_serializing_if = "Option::is_none")]
    pub out: Option<i32>,
    #[serde(rename = "lanes", skip_serializing_if = "Option::is_none")]
    pub lanes: Option<Vec<models::Lane>>,
}

impl Intersection {
    pub fn new() -> Intersection {
        Intersection {
            location: None,
            bearings: None,
            classes: None,
            entry: None,
            r#in: None,
            out: None,
            lanes: None,
        }
    }
}

