/*
 * OSRM API v5.22.0
 *
 * Open Source Routing Machine Models
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ManeuverModifier {
    #[serde(rename = "uturn")]
    Uturn,
    #[serde(rename = "sharp right")]
    SharpRight,
    #[serde(rename = "right")]
    Right,
    #[serde(rename = "slight right")]
    SlightRight,
    #[serde(rename = "straight")]
    Straight,
    #[serde(rename = "slight left")]
    SlightLeft,
    #[serde(rename = "left")]
    Left,
    #[serde(rename = "sharp left")]
    SharpLeft,

}

impl std::fmt::Display for ManeuverModifier {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Uturn => write!(f, "uturn"),
            Self::SharpRight => write!(f, "sharp right"),
            Self::Right => write!(f, "right"),
            Self::SlightRight => write!(f, "slight right"),
            Self::Straight => write!(f, "straight"),
            Self::SlightLeft => write!(f, "slight left"),
            Self::Left => write!(f, "left"),
            Self::SharpLeft => write!(f, "sharp left"),
        }
    }
}

impl Default for ManeuverModifier {
    fn default() -> ManeuverModifier {
        Self::Uturn
    }
}

