/*
 * OSRM API v5.22.0
 *
 * Extended Open Source Routing Machine Models. This includes default OSRM models, plus optional fields like MaxSpeed.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ManeuverType {
    #[serde(rename = "turn")]
    Turn,
    #[serde(rename = "new name")]
    NewName,
    #[serde(rename = "depart")]
    Depart,
    #[serde(rename = "arrive")]
    Arrive,
    #[serde(rename = "merge")]
    Merge,
    #[serde(rename = "on ramp")]
    OnRamp,
    #[serde(rename = "off ramp")]
    OffRamp,
    #[serde(rename = "fork")]
    Fork,
    #[serde(rename = "end of road")]
    EndOfRoad,
    #[serde(rename = "use lane")]
    UseLane,
    #[serde(rename = "continue")]
    Continue,
    #[serde(rename = "roundabout")]
    Roundabout,
    #[serde(rename = "rotary")]
    Rotary,
    #[serde(rename = "roundabout turn")]
    RoundaboutTurn,
    #[serde(rename = "notification")]
    Notification,
    #[serde(rename = "exit roundabout")]
    ExitRoundabout,
    #[serde(rename = "exit rotary")]
    ExitRotary,

}

impl std::fmt::Display for ManeuverType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Turn => write!(f, "turn"),
            Self::NewName => write!(f, "new name"),
            Self::Depart => write!(f, "depart"),
            Self::Arrive => write!(f, "arrive"),
            Self::Merge => write!(f, "merge"),
            Self::OnRamp => write!(f, "on ramp"),
            Self::OffRamp => write!(f, "off ramp"),
            Self::Fork => write!(f, "fork"),
            Self::EndOfRoad => write!(f, "end of road"),
            Self::UseLane => write!(f, "use lane"),
            Self::Continue => write!(f, "continue"),
            Self::Roundabout => write!(f, "roundabout"),
            Self::Rotary => write!(f, "rotary"),
            Self::RoundaboutTurn => write!(f, "roundabout turn"),
            Self::Notification => write!(f, "notification"),
            Self::ExitRoundabout => write!(f, "exit roundabout"),
            Self::ExitRotary => write!(f, "exit rotary"),
        }
    }
}

impl Default for ManeuverType {
    fn default() -> ManeuverType {
        Self::Turn
    }
}

