/*
 * OSRM API v5.22.0
 *
 * Extended Open Source Routing Machine Models. This includes default OSRM models, plus optional fields like MaxSpeed.
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MaxSpeed : The speed limit between the pair of coordinates.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaxSpeed {
    #[serde(rename = "speed", skip_serializing_if = "Option::is_none")]
    pub speed: Option<i32>,
    /// The unit of measure for the speed. Always included if speed is present.
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<Unit>,
    /// True if the speed limit is not known.
    #[serde(rename = "unknown", skip_serializing_if = "Option::is_none")]
    pub unknown: Option<bool>,
    /// True if there is no explicit speed limit (ex: some Autobahn sections)
    #[serde(rename = "none", skip_serializing_if = "Option::is_none")]
    pub none: Option<bool>,
}

impl MaxSpeed {
    /// The speed limit between the pair of coordinates.
    pub fn new() -> MaxSpeed {
        MaxSpeed {
            speed: None,
            unit: None,
            unknown: None,
            none: None,
        }
    }
}
/// The unit of measure for the speed. Always included if speed is present.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Unit {
    #[serde(rename = "km/h")]
    KmSlashH,
    #[serde(rename = "mph")]
    Mph,
}

impl Default for Unit {
    fn default() -> Unit {
        Self::KmSlashH
    }
}

