/*
 * OSRM API v5.22.0
 *
 * Extended Open Source Routing Machine Models. This includes default OSRM models, plus optional fields like MaxSpeed.
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NearestResponse {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "data_version", skip_serializing_if = "Option::is_none")]
    pub data_version: Option<String>,
    #[serde(rename = "waypoints", skip_serializing_if = "Option::is_none")]
    pub waypoints: Option<Vec<models::NearestWaypoint>>,
}

impl NearestResponse {
    pub fn new(code: Code) -> NearestResponse {
        NearestResponse {
            code,
            message: None,
            data_version: None,
            waypoints: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "Ok")]
    Ok,
    #[serde(rename = "InvalidUrl")]
    InvalidUrl,
    #[serde(rename = "InvalidService")]
    InvalidService,
    #[serde(rename = "InvalidVersion")]
    InvalidVersion,
    #[serde(rename = "InvalidOptions")]
    InvalidOptions,
    #[serde(rename = "InvalidQuery")]
    InvalidQuery,
    #[serde(rename = "InvalidValue")]
    InvalidValue,
    #[serde(rename = "NoSegment")]
    NoSegment,
    #[serde(rename = "TooBig")]
    TooBig,
    #[serde(rename = "NoRoute")]
    NoRoute,
    #[serde(rename = "NoTable")]
    NoTable,
    #[serde(rename = "NotImplemented")]
    NotImplemented,
    #[serde(rename = "NoTrips")]
    NoTrips,
}

impl Default for Code {
    fn default() -> Code {
        Self::Ok
    }
}

