/*
 * OSRM API v5.22.0
 *
 * Open Source Routing Machine Models
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteStep {
    /// The distance traveled by the route, in double meters.
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f64>,
    /// The estimated travel time, in double number of seconds.
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
    #[serde(rename = "geometry", skip_serializing_if = "Option::is_none")]
    pub geometry: Option<serde_json::Value>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    #[serde(rename = "pronunciation", skip_serializing_if = "Option::is_none")]
    pub pronunciation: Option<String>,
    #[serde(rename = "destinations", skip_serializing_if = "Option::is_none")]
    pub destinations: Option<serde_json::Value>,
    #[serde(rename = "exits", skip_serializing_if = "Option::is_none")]
    pub exits: Option<serde_json::Value>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(rename = "maneuver", skip_serializing_if = "Option::is_none")]
    pub maneuver: Option<Box<models::StepManeuver>>,
    #[serde(rename = "intersections", skip_serializing_if = "Option::is_none")]
    pub intersections: Option<Vec<models::Intersection>>,
    #[serde(rename = "rotary_name", skip_serializing_if = "Option::is_none")]
    pub rotary_name: Option<String>,
    #[serde(rename = "rotary_pronunciation", skip_serializing_if = "Option::is_none")]
    pub rotary_pronunciation: Option<String>,
    #[serde(rename = "driving_side", skip_serializing_if = "Option::is_none")]
    pub driving_side: Option<DrivingSide>,
    #[serde(rename = "voiceInstructions", skip_serializing_if = "Option::is_none")]
    pub voice_instructions: Option<Vec<models::VoiceInstruction>>,
    #[serde(rename = "bannerInstructions", skip_serializing_if = "Option::is_none")]
    pub banner_instructions: Option<Vec<models::BannerInstruction>>,
}

impl RouteStep {
    pub fn new() -> RouteStep {
        RouteStep {
            distance: None,
            duration: None,
            geometry: None,
            weight: None,
            name: None,
            r#ref: None,
            pronunciation: None,
            destinations: None,
            exits: None,
            mode: None,
            maneuver: None,
            intersections: None,
            rotary_name: None,
            rotary_pronunciation: None,
            driving_side: None,
            voice_instructions: None,
            banner_instructions: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DrivingSide {
    #[serde(rename = "left")]
    Left,
    #[serde(rename = "right")]
    Right,
}

impl Default for DrivingSide {
    fn default() -> DrivingSide {
        Self::Left
    }
}

