/*
 * OSRM API v5.22.0
 *
 * Open Source Routing Machine Models
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteLeg {
    /// The distance traveled by the route, in double meters.
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f64>,
    /// The estimated travel time, in double number of seconds.
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<models::RouteStep>>,
    #[serde(rename = "annotation", skip_serializing_if = "Option::is_none")]
    pub annotation: Option<Box<models::Annotation>>,
    /// A Mapbox and Valhalla extension which indicates which waypoints are passed through rather than creating a new leg.
    #[serde(rename = "via_waypoints", skip_serializing_if = "Option::is_none")]
    pub via_waypoints: Option<Vec<models::ViaWaypoint>>,
}

impl RouteLeg {
    pub fn new() -> RouteLeg {
        RouteLeg {
            distance: None,
            duration: None,
            weight: None,
            summary: None,
            steps: None,
            annotation: None,
            via_waypoints: None,
        }
    }
}

