/*
 * OSRM API v5.22.0
 *
 * Extended Open Source Routing Machine Models. This includes default OSRM models, plus optional fields like MaxSpeed.
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StepManeuver {
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Vec<f64>>,
    #[serde(rename = "bearing_before", skip_serializing_if = "Option::is_none")]
    pub bearing_before: Option<i32>,
    #[serde(rename = "bearing_after", skip_serializing_if = "Option::is_none")]
    pub bearing_after: Option<i32>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::ManeuverType>,
    #[serde(rename = "modifier", skip_serializing_if = "Option::is_none")]
    pub modifier: Option<models::ManeuverModifier>,
    #[serde(rename = "exit", skip_serializing_if = "Option::is_none")]
    pub exit: Option<i32>,
}

impl StepManeuver {
    pub fn new() -> StepManeuver {
        StepManeuver {
            location: None,
            bearing_before: None,
            bearing_after: None,
            r#type: None,
            modifier: None,
            exit: None,
        }
    }
}

