/*
 * OSRM API v5.22.0
 *
 * Open Source Routing Machine Models
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableResponse {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "data_version", skip_serializing_if = "Option::is_none")]
    pub data_version: Option<String>,
    /// array of arrays that stores the matrix in row-major order. durations[i][j] gives the travel time from the i-th waypoint to the j-th waypoint. Values are given in seconds.
    #[serde(rename = "durations", skip_serializing_if = "Option::is_none")]
    pub durations: Option<Vec<Vec<f64>>>,
    #[serde(rename = "distances", skip_serializing_if = "Option::is_none")]
    pub distances: Option<Vec<Vec<f64>>>,
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<models::Waypoint>>,
    #[serde(rename = "destinations", skip_serializing_if = "Option::is_none")]
    pub destinations: Option<Vec<models::Waypoint>>,
    #[serde(rename = "fallback_speed_cells", skip_serializing_if = "Option::is_none")]
    pub fallback_speed_cells: Option<Vec<Vec<i32>>>,
}

impl TableResponse {
    pub fn new(code: Code) -> TableResponse {
        TableResponse {
            code,
            message: None,
            data_version: None,
            durations: None,
            distances: None,
            sources: None,
            destinations: None,
            fallback_speed_cells: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "Ok")]
    Ok,
    #[serde(rename = "InvalidUrl")]
    InvalidUrl,
    #[serde(rename = "InvalidService")]
    InvalidService,
    #[serde(rename = "InvalidVersion")]
    InvalidVersion,
    #[serde(rename = "InvalidOptions")]
    InvalidOptions,
    #[serde(rename = "InvalidQuery")]
    InvalidQuery,
    #[serde(rename = "InvalidValue")]
    InvalidValue,
    #[serde(rename = "NoSegment")]
    NoSegment,
    #[serde(rename = "TooBig")]
    TooBig,
    #[serde(rename = "NoRoute")]
    NoRoute,
    #[serde(rename = "NoTable")]
    NoTable,
    #[serde(rename = "NotImplemented")]
    NotImplemented,
    #[serde(rename = "NoTrips")]
    NoTrips,
}

impl Default for Code {
    fn default() -> Code {
        Self::Ok
    }
}

