/*
 * OSRM API v5.22.0
 *
 * Open Source Routing Machine Models
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TripWaypoint {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Vec<f64>>,
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f64>,
    #[serde(rename = "hint", skip_serializing_if = "Option::is_none")]
    pub hint: Option<String>,
    #[serde(rename = "trips_index", skip_serializing_if = "Option::is_none")]
    pub trips_index: Option<i32>,
    #[serde(rename = "waypoint_index", skip_serializing_if = "Option::is_none")]
    pub waypoint_index: Option<i32>,
}

impl TripWaypoint {
    pub fn new() -> TripWaypoint {
        TripWaypoint {
            name: None,
            location: None,
            distance: None,
            hint: None,
            trips_index: None,
            waypoint_index: None,
        }
    }
}

