/*
 * OSRM API v5.22.0
 *
 * Open Source Routing Machine Models
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ViaWaypoint {
    #[serde(rename = "distance_from_start", skip_serializing_if = "Option::is_none")]
    pub distance_from_start: Option<f64>,
    #[serde(rename = "geometry_index", skip_serializing_if = "Option::is_none")]
    pub geometry_index: Option<i32>,
    #[serde(rename = "waypoint_index", skip_serializing_if = "Option::is_none")]
    pub waypoint_index: Option<i32>,
}

impl ViaWaypoint {
    pub fn new() -> ViaWaypoint {
        ViaWaypoint {
            distance_from_start: None,
            geometry_index: None,
            waypoint_index: None,
        }
    }
}

