/*
 * OSRM API v5.22.0
 *
 * Extended Open Source Routing Machine Models. This includes default OSRM models, plus optional fields like MaxSpeed.
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoiceInstruction {
    #[serde(rename = "distanceAlongGeometry")]
    pub distance_along_geometry: f64,
    #[serde(rename = "announcement")]
    pub announcement: String,
    #[serde(rename = "ssmlAnnouncement", skip_serializing_if = "Option::is_none")]
    pub ssml_announcement: Option<String>,
}

impl VoiceInstruction {
    pub fn new(distance_along_geometry: f64, announcement: String) -> VoiceInstruction {
        VoiceInstruction {
            distance_along_geometry,
            announcement,
            ssml_announcement: None,
        }
    }
}

